apiVersion: v1
kind: Service
metadata:
  name: video-service 
  labels:
    app: {{ .Values.video.label }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 80
    protocol: {{ .Values.service.protocol }}
    targetPort: 3001
  selector:
    app: {{ .Values.service.protocol }}