apiVersion: v1
kind: Service
metadata:
  name: video-service 
  labels:
    app: video
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 30003
    protocol: TCP
    targetPort: 80
  selector:
    app: video