apiVersion: v1
kind: Service
metadata:
  name: video-service 
  labels:
    app: video
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 80
    protocol: TCP
 
  selector:
    app: video