apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-deployment
  labels:
    app: {{ .Values.video.label }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.video.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.video.label }}
    spec:
      containers:
      - name: {{ .Values.video.label }}
        image: {{ .Values.image.video }}
        ports:
        - containerPort: 3001