apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
  namespace: 
  labels:
    app: {{ .Values.website.label }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.website.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.website.label }}
    spec:
      containers:
      - name: {{ .Values.website.label }}
        image: {{ .Values.image.website }}
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: acr-secret
