apiVersion: v1
kind: Service
metadata:
  name: website-service 
  labels:
    app: {{ .Values.website.label }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 8080
    protocol: {{ .Values.service.protocol }}
    targetPort: 80
  selector:
    app: {{ .Values.website.label }}
