apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: website
  annotations:
    argocd-image-updater.argoproj.io/image-list: website=itschaboy/sd-projeto:latest
    argocd-image-updater.argoproj.io/website.update-strategy: digest
spec:
  project: default
  source:
    repoURL: https://github.com/SistemasDistribuidos/SD_Projeto.git
    targetRevision: HEAD
    path: ./SD_Projeto
  destination: 
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
