apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
  namespace: 
  labels:
    app: website
spec:
  replicas: 3
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      namespace: website
      labels:
        app: website
    spec:
      containers:
      - name: website
        
        image: itschaboy/sd-projeto:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: acr-secret
