apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: default

images:
- name: website
  newName: itschaboy/sd-projeto
  newTag: 1bd45e28d447b58a60ba14d031d0d4f946803b05
