apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- website-Service_Deploy.yaml
images:
- name: website
  newName: itschaboy/sd-projeto
  newTag: 72582848b085dea251927b174684e3f05ef3e128
