apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
images:
- name: website
  newName: itschaboy/sd-projeto
  newTag: 006d2311e0e52b14afac123fe2cb83a52c9b6808
