apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- website-Service_Deploy.yaml
namespace: argocd
images:
- name: website
  newName: itschaboy/sd-projeto
  newTag: c1ecdcd29565b6fdb6297604f2f668cf7123d874
