apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: website
  newName: itschaboy/sd-projeto
  newTag: 5dddd3f190891e75f1ec7c4c10052918c24060aa
