apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

patches:
- deployment.yaml

images:
- name: website
  newName: itschaboy/sd-projeto
  newTag: 721de7694a47a5ae30ed224e45311c1355460706
