apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

patchesStrategicMerge:
- deployment.yaml

images:
- name: website
  newName: itschaboy/sd-projeto
  newTag: 52df4f0a129408f4600a3731181f0bfbb45ebb7b
