apiVersion: v1
kind: Service
metadata:
  name: website-service
  namespace: 
  labels:
    app: website
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: website