patchesStrategicMerge:
- deployment.yaml
images:
- name: website
  newName: itschaboy/sd-projeto
  newTag: 080fc8865d70e18e1dd992e73840cd87bd031355
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
