name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./SD_Projeto/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/sd-projeto:${{ github.sha }}
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v3
      - name: update deployment
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'SD_Projeto/deployment.yaml'
          propertyPath: 'image'
          value: ${{ secrets.DOCKER_USER }}/sd-projeto:${{ github.sha }}
          commitChange: false

    
