name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: itschaboy/sd-projeto
          tags: ${{ github.sha }}, latest
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize_version: v3.6.1

      - name: update k8s
        run: |
          cd SD_Projeto
          kustomize edit set image website=itschaboy/sd-projeto:${{ github.sha }}
          cat kustomization.yaml

      - name: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Deploy Action"
          git commit -am "change image tag"
        
      - name: push
        uses: ad-m/github-push-action@master
    
